"""
Django settings for DjangoWork project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

# 在此配置中，指定 BASE_DIR 代表当前项目的主目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k_r(fx2v7e5=-v(uh$g4-d5j)!1g(=mgzvq&3xs^=q8y=f*fac'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 设置所有ip都能进行访问
ALLOWED_HOSTS = ['*']


# Application definition

# 安装app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Seller',
    'Buyer',
]
# 安装中间件，项目一开始还用不到
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 前台发来请求会先去项目下的XXXXX/urls.py文件进行正则匹配找到应该执行的视图函数。
ROOT_URLCONF = 'DjangoWork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],  # os.path.join(BASE_DIR, 'XXXX') 拼接路径，解决路径兼容问题
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoWork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# 配置数据库，默认数据库为sqlite3，但我们更多用的是Mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""
mysql的配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'articleblog',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '0615', # 密码接收是字符串，而且我们尽量不要把密码设置为纯数字
    }
}
"""


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'       # 设置语言为中国简体汉字

TIME_ZONE = 'Asia/Shanghai'     # 设置时区为东八区上海时间

USE_I18N = True

USE_L10N = True

USE_TZ = False                  # 设置时区之后，需要更改为False，否则还会用系统默认的0时区


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# 配置静态
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# 每天文件配置，负责图片上传
MEDIA_URL = '/media/'
# 此处static是鵆数据库图片的数位，不唯一，可以换成其他目录。如果文件名不存在，将创建。
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')


# 富文本编辑器
# ckeditor上传的路径
CKEDITOR_UPLOAD_PATH = 'uploads/'
# ckeditor上传图片使用的模块（需要pip安装）
CKEDITOR_IMAGE_BACKEND = 'pillow'


# RSA
# 公钥
alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxXndEmXkxWuf1kfA4GN+qKdL8MrBRdMiPzdTIqhf6o4ngC3hnHmSigjBOURLkQyqAFzmTlOg4EZaNawdnEu+QjvAdMl15X7CRxlrIJiuzQEO/Ju1rSFSrSYkdojcNeyS6Jcn+7XeUfCRRHa0zqu47i3a9nJZQ9I0IHbX+0l6qLfY14MfxF+DLspjKyCUV7KdIO2Xu7g99+5OkAy/6JuE1a9boKQmdT569Myc2Ri7tsyuqmu/cr2wlXcn6bShg/fzDquzwdeMbg18rIQh5obdMaFpFseClAfqTJrALYp7zrpuTfX06nWUJRFtG4GWnaeR2o9Y+5p/W1FD4VvbmbdPCQIDAQAB
-----END PUBLIC KEY-----"""

# 私钥
alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAxXndEmXkxWuf1kfA4GN+qKdL8MrBRdMiPzdTIqhf6o4ngC3hnHmSigjBOURLkQyqAFzmTlOg4EZaNawdnEu+QjvAdMl15X7CRxlrIJiuzQEO/Ju1rSFSrSYkdojcNeyS6Jcn+7XeUfCRRHa0zqu47i3a9nJZQ9I0IHbX+0l6qLfY14MfxF+DLspjKyCUV7KdIO2Xu7g99+5OkAy/6JuE1a9boKQmdT569Myc2Ri7tsyuqmu/cr2wlXcn6bShg/fzDquzwdeMbg18rIQh5obdMaFpFseClAfqTJrALYp7zrpuTfX06nWUJRFtG4GWnaeR2o9Y+5p/W1FD4VvbmbdPCQIDAQABAoIBAQCyNzWNKgnZJTTdxGnL197xw/GkAMeGBXJNzNcpWv0dCGebpUyL06etDROcZAcyg1RU+YIbRBvW64b0Ez2x1SWCTrx0aXANymT4l3b3tvNiLcdhsAC4m28qtlaH5yGdRMCcSfYaktpt5oajW+H29kDyKs4GRdJLg8PpXHe0325kHdYxx++9p0g67fYkHO1lBiIPme3nXuFBP/TiUFkItBWIgUswh7zANnL4Sf42lYWcK2IAdcgQrXpFNCm4ifbrJU76bhfESfkenIQFPHHOVvMVMQ+MyRDXn/IF+RhSKOTN3FemIIt7S+WUDYFy/SGDUmcIQNQjAJpjzxViFlxP1xs1AoGBAP3T0xK9JM5IJMY6Pb3IiOpU4P5EjRjWni2wwqxrv7ZuNFoN+k584ExgYxyuiCJgrjrMYzei284lpVq14UDkI4CtGdemIUD8PAPjBEEaRH0+ElfsYdpqK3U8FwxAj37mnBcPZ45GXZ9uJAAsrQMESHNNZdJhpJq265CPetpIz4gHAoGBAMcqkHgR65SmSJnWU7pTXVBGwx6KCEt5cQgrT7kdsNZ3IwnFhHrqUTWIPa/ctSwy0Sblo6A3tDvSpZMqOg6KhlddXvdcuHurIsJ+3kDQg918XT+40q5NbZeyKiggsLNfnoJyp9yppSxNwKsSpjWKzX61BKn13G+6OjZ2sU8zDQxvAoGBAO7VvAwr0VAQbhnff2zuHnZv+20FT8aJWzke026tzCx6MeRyto3Xzq3PHDNGvm2qjwZgfxNAuJaWsapS7WrDv+w59NEHTs75B/eYSs5/SuaV22jD0adUsyOSsRUkQmFj2IeSRRyIdVuopVNMtlbaVtm3gBGfMuUpLSpO94ghbrVNAn9AkoxEYYr/puni9pouzthyLn8UZ6xIzBbZjzFJ01aCMh4qDN/m+hFaSdG2MtiKe+9TrSBf0a+dta35CLfJ/x+PM7aWfHlTnyil5nwoh3I5XRjekA2+dVwS0rDYUcD4Zwf9Qy8pW9cxhgPxcxpwQZBehFH+yLevgbFd9x2FkAerAoGBAP3TNkTaWWCqP6s8cXvgN1zRwp3jdS40A892B/tz6Fl7wtrpJrG059y9T/6YZZJXfFF4+u/0kqswBn2/qlExk6CREoTNVIbYzRTEMrN7IO38Z9UGnrk5ZQPHwo5FBNi3iJTDAqHnwncBr+5AOJB+lNzci5OaQL+p78YXRHPdYBsn
-----END RSA PRIVATE KEY-----"""